name: Snapshot

on:
  push:
    branches: [ master]

jobs:
  call-tool-snapshot:
    name: ğŸ­
    uses: cip4/.github/.github/workflows/tool-snapshot.yml@master
    with:
      apple-bundle-id: org.cip4.jdfutility
      codecov-enabled: true
      docker-build: true
      java-version: 17
      java-distribution: 'temurin'
    secrets: inherit