name: Snapshot

on:
  push:
    branches: [ master]

jobs:
  call-library-snapshot:
    name: ğŸ­
    uses: cip4/.github/.github/workflows/library-snapshot.yml@master
    with:
      codecov-enabled: true
      docker-build: true
      java-version: 17
      java-distribution: 'temurin'
    secrets: inherit